name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Snyk CLI
        run: |
          curl -sL https://snyk.io/install | bash
          export PATH=$HOME/.snyk/bin:$PATH

      - name: Verify Snyk CLI installation
        run: snyk --version

      - name: Run Snyk Security Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}  # Assurez-vous que le secret est bien nommé ici
        run: |
          snyk test --all-projects
