name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer les dépendances Python
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances du projet

      # Étape 3 : Installer le CLI de Snyk
      - name: Install Snyk CLI
        run: |
          curl -sL https://snyk.io/install | bash  # Télécharge et installe Snyk
          export PATH=$PATH:$HOME/.npm-global/bin  # Ajoute Snyk au PATH

      # Étape 4 : Vérification des vulnérabilités avec Snyk
      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true  # Continue même si une vulnérabilité est détectée
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Utilise le secret SNYK_TOKEN pour authentifier Snyk
        run: |
          snyk test --all-projects  # Lance le test de sécurité

      # Étape 5 : Optionnel - Surveiller l'état des vulnérabilités avec Snyk
      - name: Monitor with Snyk (optional)
        run: |
          snyk monitor --all-projects  # Pour suivre les vulnérabilités des dépendances dans le projet
