name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer les dépendances Python
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances du projet

      # Étape 3 : Vérification des vulnérabilités avec Snyk
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master  # Utilisation de l'action officielle Snyk
        continue-on-error: true  # Continue même si une vulnérabilité est détectée
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Utilise le secret SNYK_TOKEN pour authentifier Snyk
        with:
          command: test  # Lancer le test de sécurité

      # Étape 4 : Optionnel - Surveiller l'état des vulnérabilités avec Snyk
      - name: Monitor with Snyk (optional)
        run: |
          snyk monitor --all-projects  # Pour suivre les vulnérabilités des dépendances dans le projet
