name: Example workflow for Python using Snyk

on: 
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2  # Assurez-vous d'utiliser une version stable de l'action

      # Étape 2 : Installer les dépendances Python
      - name: Install dependencies
        run: |
          python -m venv venv  # Créer un environnement virtuel
          source venv/bin/activate  # Activer l'environnement virtuel
          pip install -r requirements.txt  # Installer les dépendances à partir de requirements.txt

      # Étape 3 : Lancer Snyk pour vérifier les vulnérabilités
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master  # Utilise l'action officielle de Snyk pour Python
        continue-on-error: true  # Pour s'assurer que l'upload du SARIF se fasse même en cas d'erreurs
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Le secret Snyk Token pour l'authentification
        with:
          command: test  # Lance le test de sécurité sur les dépendances
