name: Snyk Security Scan with Automated Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk_and_tests:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Étape 3 : Installer les dépendances Python
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Scanner les vulnérabilités Python avec Snyk
      - name: Snyk scan (Python)
        uses: snyk/actions/python@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=requirements.txt 

      

      # Étape 6 : Configurer Node.js (React frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Étape 7 : Installer les dépendances React (frontend)
      - name: Install React dependencies
        working-directory: ./frontend-react
        run: npm install

      # Étape 8 : Scanner les vulnérabilités Node.js (frontend)
      - name: Snyk scan (Node.js)
        run: |
          cd frontend-react
          npx snyk test --file=package.json 
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

